"""Initial schema with all tables

Revision ID: 94e67d473306
Revises:
Create Date: 2026-01-12 13:11:28.484745

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94e67d473306"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("steps", sa.Integer(), nullable=True),
        sa.Column("distance_meters", sa.Float(), nullable=True),
        sa.Column("calories_active", sa.Integer(), nullable=True),
        sa.Column("calories_total", sa.Integer(), nullable=True),
        sa.Column("active_time_seconds", sa.Integer(), nullable=True),
        sa.Column("activity_score", sa.Integer(), nullable=True),
        sa.Column("inactivity_alerts", sa.Integer(), nullable=True),
        sa.Column(
            "user_id",
            sa.String(length=255),
            nullable=False,
            comment="Polar user ID or Laravel user UUID",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_activity_user_date"),
        comment="Daily activity with steps, calories, and zones",
    )
    op.create_index(op.f("ix_activity_date"), "activity", ["date"], unique=False)
    op.create_index(op.f("ix_activity_user_id"), "activity", ["user_id"], unique=False)
    op.create_table(
        "activity_samples",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_steps", sa.Integer(), nullable=False, comment="Total steps for the day"),
        sa.Column(
            "interval_ms",
            sa.Integer(),
            nullable=False,
            comment="Sample interval (60000ms = 1 minute)",
        ),
        sa.Column(
            "sample_count", sa.Integer(), nullable=False, comment="Number of samples in the day"
        ),
        sa.Column(
            "samples_json",
            sa.Text(),
            nullable=True,
            comment="JSON array of step samples with timestamps",
        ),
        sa.Column(
            "user_id",
            sa.String(length=255),
            nullable=False,
            comment="Polar user ID or Laravel user UUID",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_activity_samples_user_date"),
        comment="Minute-by-minute activity samples with step data",
    )
    op.create_index(op.f("ix_activity_samples_date"), "activity_samples", ["date"], unique=False)
    op.create_index(
        op.f("ix_activity_samples_user_id"), "activity_samples", ["user_id"], unique=False
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("polar_client_id", sa.String(length=255), nullable=True),
        sa.Column("polar_client_secret_encrypted", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "body_temperature",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.String(length=100), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "measurement_type",
            sa.String(length=50),
            nullable=False,
            comment="e.g., CONTINUOUS, SPOT",
        ),
        sa.Column(
            "sensor_location", sa.String(length=50), nullable=False, comment="e.g., WRIST, FINGER"
        ),
        sa.Column("temp_min", sa.Float(), nullable=True, comment="Minimum temperature (Celsius)"),
        sa.Column("temp_max", sa.Float(), nullable=True, comment="Maximum temperature (Celsius)"),
        sa.Column("temp_avg", sa.Float(), nullable=True, comment="Average temperature (Celsius)"),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("samples_json", sa.Text(), nullable=True, comment="Temperature samples as JSON"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "user_id",
            sa.String(length=255),
            nullable=False,
            comment="Polar user ID or Laravel user UUID",
        ),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_index(
        op.f("ix_body_temperature_user_id"), "body_temperature", ["user_id"], unique=False
    )
    op.create_table(
        "cardio_load",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "cardio_load",
            sa.Float(),
            nullable=True,
            comment="Overall cardio load value (-1.0 if not available)",
        ),
        sa.Column(
            "cardio_load_status",
            sa.String(length=50),
            nullable=True,
            comment="Load status (e.g., LOAD_STATUS_NOT_AVAILABLE)",
        ),
        sa.Column(
            "cardio_load_ratio",
            sa.Float(),
            nullable=True,
            comment="Load ratio (-1.0 if not available)",
        ),
        sa.Column("strain", sa.Float(), nullable=True, comment="Training strain value"),
        sa.Column(
            "tolerance",
            sa.Float(),
            nullable=True,
            comment="Training tolerance value (-1.0 if not available)",
        ),
        sa.Column("load_very_low", sa.Float(), nullable=True, comment="Very low intensity load"),
        sa.Column("load_low", sa.Float(), nullable=True, comment="Low intensity load"),
        sa.Column("load_medium", sa.Float(), nullable=True, comment="Medium intensity load"),
        sa.Column("load_high", sa.Float(), nullable=True, comment="High intensity load"),
        sa.Column("load_very_high", sa.Float(), nullable=True, comment="Very high intensity load"),
        sa.Column(
            "user_id",
            sa.String(length=255),
            nullable=False,
            comment="Polar user ID or Laravel user UUID",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_cardio_load_user_date"),
        comment="Cardio load with strain, tolerance, and load distribution",
    )
    op.create_index(op.f("ix_cardio_load_date"), "cardio_load", ["date"], unique=False)
    op.create_index(op.f("ix_cardio_load_user_id"), "cardio_load", ["user_id"], unique=False)
    op.create_table(
        "continuous_heart_rate",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False, comment="Number of HR samples"),
        sa.Column("hr_min", sa.Integer(), nullable=True, comment="Minimum heart rate"),
        sa.Column("hr_max", sa.Integer(), nullable=True, comment="Maximum heart rate"),
        sa.Column("hr_avg", sa.Integer(), nullable=True, comment="Average heart rate"),
        sa.Column(
            "samples_json",
            sa.Text(),
            nullable=True,
            comment="JSON array of HR samples with timestamps",
        ),
        sa.Column(
            "user_id",
            sa.String(length=255),
            nullable=False,
            comment="Polar user ID or Laravel user UUID",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_continuous_hr_user_date"),
        comment="All-day heart rate samples at 5-minute intervals",
    )
    op.create_index(
        op.f("ix_continuous_heart_rate_date"), "continuous_heart_rate", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_continuous_heart_rate_user_id"), "continuous_heart_rate", ["user_id"], unique=False
    )
    op.create_table(
        "ecg",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.String(length=100), nullable=False),
        sa.Column("test_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone_offset_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "avg_heart_rate", sa.Integer(), nullable=False, comment="Average HR during ECG test"
        ),
        sa.Column("hrv_ms", sa.Float(), nullable=False, comment="HRV (RMSSD) in ms"),
        sa.Column(
            "hrv_level",
            sa.String(length=50),
            nullable=False,
            comment="HRV classification: LOW, NORMAL, HIGH",
        ),
        sa.Column("rri_ms", sa.Float(), nullable=False, comment="R-R interval in ms"),
        sa.Column("ptt_systolic_ms", sa.Float(), nullable=True, comment="PTT systolic"),
        sa.Column("ptt_diastolic_ms", sa.Float(), nullable=True, comment="PTT diastolic"),
        sa.Column("ptt_quality_index", sa.Float(), nullable=True, comment="PTT quality index"),
        sa.Column("sample_count", sa.Integer(), nullable=False, comment="Number of ECG samples"),
        sa.Column("samples_json", sa.Text(), nullable=True, comment="ECG waveform samples as JSON"),
        sa.Column(
            "quality_json",
            sa.Text(),
            nullable=True,
            comment="Quality measurements over time as JSON",
        ),
        sa.Column(
            "duration_seconds", sa.Float(), nullable=True, comment="Test duration in seconds"
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "user_id",
            sa.String(length=255),
            nullable=False,
            comment="Polar user ID or Laravel user UUID",
        ),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_index(op.f("ix_ecg_user_id"), "ecg", ["user_id"], unique=False)
    op.create_table(
        "exercise",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("polar_exercise_id", sa.String(length=255), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stop_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("sport", sa.String(length=100), nullable=True),
        sa.Column("detailed_sport_info", sa.String(length=255), nullable=True),
        sa.Column("distance_meters", sa.Float(), nullable=True),
        sa.Column("average_speed_mps", sa.Float(), nullable=True),
        sa.Column("max_speed_mps", sa.Float(), nullable=True),
        sa.Column("average_heart_rate", sa.Integer(), nullable=True),
        sa.Column("max_heart_rate", sa.Integer(), nullable=True),
        sa.Column("min_heart_rate", sa.Integer(), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("training_load", sa.Float(), nullable=True),
        sa.Column("ascent_meters", sa.Float(), nullable=True),
        sa.Column("descent_meters", sa.Float(), nullable=True),
        sa.Column("average_cadence", sa.Float(), nullable=True),
        sa.Column("max_cadence", sa.Integer(), nullable=True),
        sa.Column("average_power", sa.Float(), nullable=True),
        sa.Column("max_power", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("has_route", sa.Boolean(), nullable=False),
        sa.Column(
            "user_id",
            sa.String(length=255),
            nullable=False,
            comment="Polar user ID or Laravel user UUID",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "polar_exercise_id", name="uq_exercise_user_polar_id"),
        comment="Exercise/workout data with detailed metrics",
    )
    op.create_index(
        op.f("ix_exercise_polar_exercise_id"), "exercise", ["polar_exercise_id"], unique=False
    )
    op.create_index(op.f("ix_exercise_start_time"), "exercise", ["start_time"], unique=False)
    op.create_index(op.f("ix_exercise_user_id"), "exercise", ["user_id"], unique=False)
    op.create_table(
        "nightly_recharge",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("ans_charge", sa.Float(), nullable=True),
        sa.Column(
            "ans_charge_status",
            sa.Integer(),
            nullable=True,
            comment="-3 to +3: much compromised to greatly above",
        ),
        sa.Column("hrv_avg", sa.Float(), nullable=True),
        sa.Column("hrv_status", sa.Integer(), nullable=True),
        sa.Column("breathing_rate_avg", sa.Float(), nullable=True),
        sa.Column("breathing_rate_status", sa.Integer(), nullable=True),
        sa.Column("heart_rate_avg", sa.Float(), nullable=True),
        sa.Column("heart_rate_status", sa.Integer(), nullable=True),
        sa.Column("sleep_score", sa.Integer(), nullable=True),
        sa.Column("sleep_charge", sa.Float(), nullable=True),
        sa.Column("sleep_charge_status", sa.Integer(), nullable=True),
        sa.Column(
            "user_id",
            sa.String(length=255),
            nullable=False,
            comment="Polar user ID or Laravel user UUID",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_recharge_user_date"),
        comment="Nightly Recharge with ANS charge and recovery status",
    )
    op.create_index(op.f("ix_nightly_recharge_date"), "nightly_recharge", ["date"], unique=False)
    op.create_index(
        op.f("ix_nightly_recharge_user_id"), "nightly_recharge", ["user_id"], unique=False
    )
    op.create_table(
        "skin_temperature",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sleep_date", sa.Date(), nullable=False),
        sa.Column(
            "temperature_celsius",
            sa.Float(),
            nullable=False,
            comment="Skin temperature during sleep",
        ),
        sa.Column(
            "deviation_from_baseline",
            sa.Float(),
            nullable=False,
            comment="Deviation from baseline (Celsius)",
        ),
        sa.Column(
            "is_elevated", sa.Integer(), nullable=False, comment="Temperature > 0.5C above baseline"
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "user_id",
            sa.String(length=255),
            nullable=False,
            comment="Polar user ID or Laravel user UUID",
        ),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_index(
        op.f("ix_skin_temperature_user_id"), "skin_temperature", ["user_id"], unique=False
    )
    op.create_table(
        "sleep",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("sleep_start_time", sa.String(length=50), nullable=True),
        sa.Column("sleep_end_time", sa.String(length=50), nullable=True),
        sa.Column("total_sleep_seconds", sa.Integer(), nullable=True),
        sa.Column("light_sleep_seconds", sa.Integer(), nullable=True),
        sa.Column("deep_sleep_seconds", sa.Integer(), nullable=True),
        sa.Column("rem_sleep_seconds", sa.Integer(), nullable=True),
        sa.Column("interruptions_seconds", sa.Integer(), nullable=True),
        sa.Column("sleep_score", sa.Integer(), nullable=True),
        sa.Column("sleep_rating", sa.Integer(), nullable=True),
        sa.Column("hrv_avg", sa.Float(), nullable=True),
        sa.Column("hrv_samples", sa.Integer(), nullable=True),
        sa.Column("heart_rate_avg", sa.Float(), nullable=True),
        sa.Column("heart_rate_min", sa.Integer(), nullable=True),
        sa.Column("heart_rate_max", sa.Integer(), nullable=True),
        sa.Column("breathing_rate_avg", sa.Float(), nullable=True),
        sa.Column("skin_temperature_avg", sa.Float(), nullable=True),
        sa.Column(
            "user_id",
            sa.String(length=255),
            nullable=False,
            comment="Polar user ID or Laravel user UUID",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_sleep_user_date"),
        comment="Sleep data with HRV and sleep stages",
    )
    op.create_index(op.f("ix_sleep_date"), "sleep", ["date"], unique=False)
    op.create_index(op.f("ix_sleep_user_id"), "sleep", ["user_id"], unique=False)
    op.create_table(
        "sleepwise_alertness",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("grade", sa.Float(), nullable=False),
        sa.Column("grade_validity_seconds", sa.Integer(), nullable=False),
        sa.Column("grade_type", sa.String(length=50), nullable=False),
        sa.Column("grade_classification", sa.String(length=50), nullable=False),
        sa.Column("validity", sa.String(length=50), nullable=False),
        sa.Column("sleep_inertia", sa.String(length=50), nullable=False),
        sa.Column("sleep_type", sa.String(length=50), nullable=False),
        sa.Column("result_type", sa.String(length=50), nullable=False),
        sa.Column("period_start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sleep_period_start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sleep_period_end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sleep_timezone_offset_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "hourly_data_json",
            sa.Text(),
            nullable=True,
            comment="JSON array of hourly alertness predictions",
        ),
        sa.Column(
            "user_id",
            sa.String(length=255),
            nullable=False,
            comment="Polar user ID or Laravel user UUID",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "period_start_time", name="uq_sleepwise_alertness_user_period"
        ),
        comment="SleepWise alertness predictions with hourly data",
    )
    op.create_index(
        op.f("ix_sleepwise_alertness_period_start_time"),
        "sleepwise_alertness",
        ["period_start_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sleepwise_alertness_user_id"), "sleepwise_alertness", ["user_id"], unique=False
    )
    op.create_table(
        "sleepwise_bedtime",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("validity", sa.String(length=50), nullable=False),
        sa.Column(
            "quality",
            sa.String(length=100),
            nullable=False,
            comment="Quality assessment (e.g., CIRCADIAN_BEDTIME_QUALITY_COMPROMISED)",
        ),
        sa.Column(
            "result_type", sa.String(length=50), nullable=False, comment="HISTORY or PREDICTION"
        ),
        sa.Column("period_start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("preferred_sleep_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("preferred_sleep_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sleep_gate_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sleep_gate_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sleep_timezone_offset_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "user_id",
            sa.String(length=255),
            nullable=False,
            comment="Polar user ID or Laravel user UUID",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "period_start_time", name="uq_sleepwise_bedtime_user_period"
        ),
        comment="SleepWise circadian bedtime recommendations",
    )
    op.create_index(
        op.f("ix_sleepwise_bedtime_period_start_time"),
        "sleepwise_bedtime",
        ["period_start_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sleepwise_bedtime_user_id"), "sleepwise_bedtime", ["user_id"], unique=False
    )
    op.create_table(
        "spo2",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.String(length=100), nullable=False),
        sa.Column("test_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone_offset_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "blood_oxygen_percent", sa.Integer(), nullable=False, comment="SpO2 percentage (0-100)"
        ),
        sa.Column(
            "spo2_class",
            sa.String(length=50),
            nullable=False,
            comment="Classification: NORMAL, LOW, etc.",
        ),
        sa.Column(
            "spo2_deviation", sa.String(length=50), nullable=True, comment="Deviation from baseline"
        ),
        sa.Column(
            "quality_percent", sa.Float(), nullable=True, comment="Signal quality percentage"
        ),
        sa.Column(
            "avg_heart_rate", sa.Integer(), nullable=True, comment="Average HR during SpO2 test"
        ),
        sa.Column("hrv_ms", sa.Float(), nullable=True, comment="HRV during test in ms"),
        sa.Column(
            "hrv_deviation",
            sa.String(length=50),
            nullable=True,
            comment="HRV deviation from baseline",
        ),
        sa.Column(
            "altitude_meters", sa.Float(), nullable=True, comment="Altitude during measurement"
        ),
        sa.Column(
            "test_status", sa.String(length=50), nullable=False, comment="Test completion status"
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "user_id",
            sa.String(length=255),
            nullable=False,
            comment="Polar user ID or Laravel user UUID",
        ),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_index(op.f("ix_spo2_user_id"), "spo2", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("polar_user_id", sa.String(length=255), nullable=False),
        sa.Column("access_token_encrypted", sa.Text(), nullable=False),
        sa.Column("refresh_token_encrypted", sa.Text(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_polar_user_id"), "users", ["polar_user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_polar_user_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_spo2_user_id"), table_name="spo2")
    op.drop_table("spo2")
    op.drop_index(op.f("ix_sleepwise_bedtime_user_id"), table_name="sleepwise_bedtime")
    op.drop_index(op.f("ix_sleepwise_bedtime_period_start_time"), table_name="sleepwise_bedtime")
    op.drop_table("sleepwise_bedtime")
    op.drop_index(op.f("ix_sleepwise_alertness_user_id"), table_name="sleepwise_alertness")
    op.drop_index(
        op.f("ix_sleepwise_alertness_period_start_time"), table_name="sleepwise_alertness"
    )
    op.drop_table("sleepwise_alertness")
    op.drop_index(op.f("ix_sleep_user_id"), table_name="sleep")
    op.drop_index(op.f("ix_sleep_date"), table_name="sleep")
    op.drop_table("sleep")
    op.drop_index(op.f("ix_skin_temperature_user_id"), table_name="skin_temperature")
    op.drop_table("skin_temperature")
    op.drop_index(op.f("ix_nightly_recharge_user_id"), table_name="nightly_recharge")
    op.drop_index(op.f("ix_nightly_recharge_date"), table_name="nightly_recharge")
    op.drop_table("nightly_recharge")
    op.drop_index(op.f("ix_exercise_user_id"), table_name="exercise")
    op.drop_index(op.f("ix_exercise_start_time"), table_name="exercise")
    op.drop_index(op.f("ix_exercise_polar_exercise_id"), table_name="exercise")
    op.drop_table("exercise")
    op.drop_index(op.f("ix_ecg_user_id"), table_name="ecg")
    op.drop_table("ecg")
    op.drop_index(op.f("ix_continuous_heart_rate_user_id"), table_name="continuous_heart_rate")
    op.drop_index(op.f("ix_continuous_heart_rate_date"), table_name="continuous_heart_rate")
    op.drop_table("continuous_heart_rate")
    op.drop_index(op.f("ix_cardio_load_user_id"), table_name="cardio_load")
    op.drop_index(op.f("ix_cardio_load_date"), table_name="cardio_load")
    op.drop_table("cardio_load")
    op.drop_index(op.f("ix_body_temperature_user_id"), table_name="body_temperature")
    op.drop_table("body_temperature")
    op.drop_table("app_settings")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_activity_samples_user_id"), table_name="activity_samples")
    op.drop_index(op.f("ix_activity_samples_date"), table_name="activity_samples")
    op.drop_table("activity_samples")
    op.drop_index(op.f("ix_activity_user_id"), table_name="activity")
    op.drop_index(op.f("ix_activity_date"), table_name="activity")
    op.drop_table("activity")
    # ### end Alembic commands ###
